# Generated by Django 5.1.5 on 2025-01-19 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_refreshtoken_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 22, 34, 6, 95504)),
        ),
    ]
