# Generated by Django 5.1.5 on 2025-01-20 15:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refreshtoken_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expiry_time',
            field=models.DateTimeField(default=api.models.get_expiry_time),
        ),
    ]
